### ISSUE TITLE
Checkout is faling on latest Jenkins

### ISSUE THREAD

**Issue by viyh** [jenkinsci/google-source-plugin#7]
Using Jenkins 2.187, this plugin now fails upon attempting and "checkout scm" in the Jenkinsfile:

```
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
    at jenkins.model.Jenkins.get(Jenkins.java:772)
    at hudson.model.Hudson.getInstance(Hudson.java:77)
    at com.google.jenkins.plugins.source.GoogleRobotUsernamePassword.areOnMaster(GoogleRobotUsernamePassword.java:146)
    at com.google.jenkins.plugins.source.GoogleRobotUsernamePassword.readObject(GoogleRobotUsernamePassword.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1933)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
    at hudson.remoting.UserRequest.deserialize(UserRequest.java:245)
    at hudson.remoting.UserRequest.perform(UserRequest.java:159)
```

**Comment by bgeesaman** [comment]
Rolling back from jenkins/jenkins:2.187 to jenkins/jenkins:2.180 removes this issue.  I tried 2.186 and 2.185 (both failed) and then 2.180 worked.

**Comment by bgeesaman** [comment]
Jenkins version `2.183` works, and `2.184+` is when it broke.

**Comment by viyh** [comment]
> Jenkins version `2.183` works, and `2.184+` is when it broke.

Thanks for that, i can get by. Any idea how to fix it so that I can continue to stay up to date with upgrades? This is fairly critical functionality for the workloads that I manage on GCP...

**Comment by mrothroc** [comment]
I have the same issue with image jenkins/jenkins:lts.  Following the above I tried to roll back to jenkins/jenkins:2.183 but that did not resolve it.  It works only at jenkins/jenkins:2.182.

It would be good to be able to update but I'm stuck until Jenkins can pull from GSR.

**Comment by viyh** [comment]
Any update on this? Now that LTS has been bumped to 2.190, the LTS version no longer works with the plugin either.

**Comment by viglesiasce** [comment]
@viyh version 0.4 with the fix has now been released. Please test it out and let us know if you have any issues.

**Comment by viyh** [comment]
I've installed it on one instance of Jenkins and it seems to work, thanks a ton! I'll be rolling it out across a bunch of instances over the coming days/weeks and I'll reopen an issue if anything comes up.
